-- MySQL Script generated by MySQL Workbench
-- Wed Nov 28 21:09:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo_unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_unidad` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidad_academica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidad_academica` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_unidad` INT NOT NULL,
  `codigo` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_unidad_academica_tipo_unidad1_idx` (`id_tipo_unidad` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `fk_unidad_academica_tipo_unidad1`
    FOREIGN KEY (`id_tipo_unidad`)
    REFERENCES `mydb`.`tipo_unidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facultad` (
  `id_unidad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_unidad`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_Facultad_Unidad_academica1_idx` (`id_unidad` ASC),
  CONSTRAINT `fk_Facultad_Unidad_academica1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `mydb`.`unidad_academica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`programa` (
  `id_unidad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `id_facultad` INT NOT NULL,
  PRIMARY KEY (`id_unidad`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_programa_Unidad_academica1_idx` (`id_unidad` ASC),
  INDEX `fk_programa_Facultad1_idx` (`id_facultad` ASC),
  CONSTRAINT `fk_programa_Facultad1`
    FOREIGN KEY (`id_facultad`)
    REFERENCES `mydb`.`facultad` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programa_Unidad_academica1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `mydb`.`unidad_academica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departamento` (
  `id_unidad` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `id_facultad` INT NOT NULL,
  PRIMARY KEY (`id_unidad`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_Departamento_Unidad_academica1_idx` (`id_unidad` ASC),
  INDEX `fk_Departamento_Facultad1_idx` (`id_facultad` ASC),
  CONSTRAINT `fk_Departamento_Facultad1`
    FOREIGN KEY (`id_facultad`)
    REFERENCES `mydb`.`facultad` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departamento_Unidad_academica1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `mydb`.`unidad_academica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria_grupo` (
  `id_categoria` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modalidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modalidad` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_investigador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_investigador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_identificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_identificacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `fecha_nacimiento` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `numero_identificacion` VARCHAR(45) NULL,
  `tipo_identificacion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_persona_tipo_identificacion1_idx` (`tipo_identificacion` ASC),
  UNIQUE INDEX `numero_identificacion_UNIQUE` (`numero_identificacion` ASC),
  CONSTRAINT `fk_persona_tipo_identificacion1`
    FOREIGN KEY (`tipo_identificacion`)
    REFERENCES `mydb`.`tipo_identificacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_participante` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participante` (
  `id_participante` INT NOT NULL,
  `tipo_participante` INT NOT NULL,
  PRIMARY KEY (`id_participante`),
  INDEX `fk_participante_tipo_participante1_idx` (`tipo_participante` ASC),
  CONSTRAINT `fk_participante_persona1`
    FOREIGN KEY (`id_participante`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_tipo_participante1`
    FOREIGN KEY (`tipo_participante`)
    REFERENCES `mydb`.`tipo_participante` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`investigador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`investigador` (
  `id_investigador` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  INDEX `fk_investigador_tipo1_idx` (`id_tipo` ASC),
  PRIMARY KEY (`id_investigador`),
  CONSTRAINT `fk_investigador_tipo1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `mydb`.`tipo_investigador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_investigador_participante1`
    FOREIGN KEY (`id_investigador`)
    REFERENCES `mydb`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`docente_ufps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`docente_ufps` (
  `id_investigador` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `id_departamento` INT NOT NULL,
  `id_modalidad` INT NOT NULL,
  INDEX `fk_docente_ufps_Departamento1_idx` (`id_departamento` ASC),
  INDEX `fk_docente_ufps_modalidad1_idx` (`id_modalidad` ASC),
  PRIMARY KEY (`id_investigador`),
  CONSTRAINT `fk_docente_ufps_Departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `mydb`.`departamento` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docente_ufps_modalidad1`
    FOREIGN KEY (`id_modalidad`)
    REFERENCES `mydb`.`modalidad` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docente_ufps_investigador1`
    FOREIGN KEY (`id_investigador`)
    REFERENCES `mydb`.`investigador` (`id_investigador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_investigacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo_investigacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `sigla` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  `codigo_colciencias` VARCHAR(45) NULL,
  `clasificado` INT NULL,
  `correo` VARCHAR(45) NULL,
  `id_categoria` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  `director_grupo` INT NOT NULL,
  `activo` INT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `fk_Grupo de Investigacion_Categoria_grupo1_idx` (`id_categoria` ASC),
  INDEX `fk_Grupo_Investigacion_Unidad_academica1_idx` (`id_unidad` ASC),
  INDEX `fk_Grupo_Investigacion_docente_ufps1_idx` (`director_grupo` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC),
  UNIQUE INDEX `codigo_colciencias_UNIQUE` (`codigo_colciencias` ASC),
  CONSTRAINT `fk_Grupo de Investigacion_Categoria_grupo1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `mydb`.`categoria_grupo` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Investigacion_Unidad_academica1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `mydb`.`unidad_academica` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Grupo_Investigacion_docente_ufps1`
    FOREIGN KEY (`director_grupo`)
    REFERENCES `mydb`.`docente_ufps` (`id_investigador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_linea`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_linea` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linea_investigacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linea_investigacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(500) NULL,
  `descripcion` VARCHAR(200) NULL,
  `id_tipo_linea` INT NOT NULL,
  `lider_linea` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_linea_investigacion_tipo_linea1_idx` (`id_tipo_linea` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  CONSTRAINT `fk_linea_investigacion_tipo_linea1`
    FOREIGN KEY (`id_tipo_linea`)
    REFERENCES `mydb`.`tipo_linea` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linea_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linea_grupo` (
  `id_linea` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_linea`),
  INDEX `fk_linea_grupo_Grupo_Investigacion1_idx` (`id_grupo` ASC),
  CONSTRAINT `fk_linea_grupo_linea_investigacion1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `mydb`.`linea_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_linea_grupo_Grupo_Investigacion1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`semillero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NULL,
  `nombre` VARCHAR(200) NULL,
  `sigla` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(200) NULL,
  `fecha_creacion` VARCHAR(45) NULL,
  `id_grupo` INT NOT NULL,
  `correo` VARCHAR(200) NULL,
  `id_linea_grupo` INT NOT NULL,
  `id_director` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Semillero_Grupo_Investigacion1_idx` (`id_grupo` ASC),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  INDEX `fk_Semillero_linea_grupo1_idx` (`id_linea_grupo` ASC),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  UNIQUE INDEX `sigla_UNIQUE` (`sigla` ASC),
  INDEX `fk_semillero_docente_ufps1_idx` (`id_director` ASC),
  UNIQUE INDEX `id_director_UNIQUE` (`id_director` ASC),
  CONSTRAINT `fk_Semillero_Grupo_Investigacion1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Semillero_linea_grupo1`
    FOREIGN KEY (`id_linea_grupo`)
    REFERENCES `mydb`.`linea_grupo` (`id_linea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semillero_docente_ufps1`
    FOREIGN KEY (`id_director`)
    REFERENCES `mydb`.`docente_ufps` (`id_investigador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipoproyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipoproyecto` (
  `id` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_participacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_participacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `n_contrato` VARCHAR(45) NULL,
  `titulo` VARCHAR(1000) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_final` VARCHAR(45) NULL,
  `tiempo_ejecucion` VARCHAR(45) NULL DEFAULT NULL,
  `costoTotal` INT NULL,
  `porcentaje_cumplimiento` INT NULL,
  `resumen` VARCHAR(250) NULL DEFAULT NULL,
  `justificacion` VARCHAR(300) NULL DEFAULT NULL,
  `objetivo_general` VARCHAR(200) NULL DEFAULT NULL,
  `resultados_esperados` VARCHAR(200) NULL,
  `documento_proyecto` VARCHAR(100) NULL DEFAULT NULL,
  `tipo_participacion_id` INT NULL DEFAULT NULL,
  `estado` INT NULL DEFAULT 0,
  `id_linea` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC),
  INDEX `fk_Proyecto_linea_investigacion1_idx` (`id_linea` ASC),
  INDEX `fk_proyecto_tipo_participacion1_idx` (`tipo_participacion_id` ASC),
  INDEX `fk_proyecto_tipoProyecto1_idx` (`id_tipo` ASC),
  CONSTRAINT `fk_Proyecto_linea_investigacion1`
    FOREIGN KEY (`id_linea`)
    REFERENCES `mydb`.`linea_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_tipoProyecto1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `mydb`.`tipoproyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_tipo_participacion1`
    FOREIGN KEY (`tipo_participacion_id`)
    REFERENCES `mydb`.`tipo_participacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_grupo` (
  `id_proyecto` INT NOT NULL,
  `id_grupo` INT NOT NULL,
  PRIMARY KEY (`id_proyecto`, `id_grupo`),
  INDEX `fk_Proyecto_has_Grupo de Investigacion_Grupo de Investigaci_idx` (`id_grupo` ASC),
  INDEX `fk_Proyecto_has_Grupo de Investigacion_Proyecto1_idx` (`id_proyecto` ASC),
  CONSTRAINT `fk_Proyecto_has_Grupo de Investigacion_Grupo de Investigacion1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Proyecto_has_Grupo de Investigacion_Proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apoyo_programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apoyo_programa` (
  `id_grupo` INT NOT NULL,
  `id_unidad` INT NOT NULL,
  PRIMARY KEY (`id_grupo`, `id_unidad`),
  INDEX `fk_programa_has_Grupo de Investigacion_Grupo de Investigaci_idx` (`id_grupo` ASC),
  INDEX `fk_apoyo_programa_programa1_idx` (`id_unidad` ASC),
  CONSTRAINT `fk_programa_has_Grupo de Investigacion_Grupo de Investigacion1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_apoyo_programa_programa1`
    FOREIGN KEY (`id_unidad`)
    REFERENCES `mydb`.`programa` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipologia_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipologia_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subtipo_tipologia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subtipo_tipologia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `tipologia_producto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subtipologia_tipologia_producto1_idx` (`tipologia_producto_id` ASC),
  CONSTRAINT `fk_subtipologia_tipologia_producto1`
    FOREIGN KEY (`tipologia_producto_id`)
    REFERENCES `mydb`.`tipologia_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `subtipo_tipologia_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `subtipo_tipologia_id`),
  INDEX `fk_tipo_producto_subtipo_tipologia1_idx` (`subtipo_tipologia_id` ASC),
  CONSTRAINT `fk_tipo_producto_subtipo_tipologia1`
    FOREIGN KEY (`subtipo_tipologia_id`)
    REFERENCES `mydb`.`subtipo_tipologia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(1000) NULL,
  `id_proyecto` INT NOT NULL,
  `descripcion` VARCHAR(1000) NULL,
  `id_tipo_producto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Producto_Proyecto1_idx` (`id_proyecto` ASC),
  INDEX `fk_producto_tipo_producto1_idx` (`id_tipo_producto` ASC),
  CONSTRAINT `fk_Producto_Proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_tipo_producto1`
    FOREIGN KEY (`id_tipo_producto`)
    REFERENCES `mydb`.`tipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`financiamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`financiamiento` (
  `id` INT NOT NULL,
  `fuente` VARCHAR(45) NULL,
  `valor` INT NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_financiamiento_Proyecto1_idx` (`id_proyecto` ASC),
  CONSTRAINT `fk_financiamiento_Proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_referencia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`articulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`articulo` (
  `id_producto` INT NOT NULL,
  `tipo_referencia` INT NOT NULL,
  `nombre_revista` VARCHAR(700) NULL,
  `titulo_articulo` VARCHAR(700) NULL,
  `autores` VARCHAR(700) NULL,
  `anio` VARCHAR NULL,
  `mes` VARCHAR NULL,
  `volumen` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  `paginas_ini` VARCHAR(45) NULL,
  `paginas_final` VARCHAR(45) NULL,
  `ISSN` VARCHAR(45) NULL,
  `paginaWeb` VARCHAR(1000) NULL,
  `DOI` VARCHAR(100) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_articulo_producto1_idx` (`id_producto` ASC),
  INDEX `fk_articulo_tipo1_idx` (`tipo_referencia` ASC),
  CONSTRAINT `fk_articulo_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo_tipo1`
    FOREIGN KEY (`tipo_referencia`)
    REFERENCES `mydb`.`tipo_referencia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_desarrollo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_desarrollo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`libro` (
  `id_producto` INT NOT NULL,
  `titulo` VARCHAR(1000) NULL,
  `ISBN` VARCHAR(45) NULL,
  `fecha_publica` VARCHAR(45) NULL,
  `autores` VARCHAR(45) NULL,
  `editorial` VARCHAR(45) NULL,
  `lugar_publica` VARCHAR(45) NULL,
  `certificacion_entidad` VARCHAR(45) NULL,
  `curriculo` VARCHAR(45) NULL,
  `tipo_desarrollo_id` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_libro_producto1_idx` (`id_producto` ASC),
  INDEX `fk_libro_tipo_desarrollo1_idx` (`tipo_desarrollo_id` ASC),
  CONSTRAINT `fk_libro_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_tipo_desarrollo1`
    FOREIGN KEY (`tipo_desarrollo_id`)
    REFERENCES `mydb`.`tipo_desarrollo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`capitulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`capitulo` (
  `producto_id` INT NOT NULL,
  `titulo_libro` VARCHAR(45) NULL,
  `titulo_capitulo` VARCHAR(45) NULL,
  `ISBN_librol` VARCHAR(45) NULL,
  `fecha_publica` VARCHAR(45) NULL,
  `autores` VARCHAR(45) NULL,
  `editorial` VARCHAR(45) NULL,
  `lugar_publica` VARCHAR(45) NULL,
  `tipo_desarrollo_id` INT NOT NULL,
  `certificacion_entidad` VARCHAR(45) NULL,
  `curriculo_capitulo` VARCHAR(45) NULL,
  PRIMARY KEY (`producto_id`),
  INDEX `fk_capitulo_producto1_idx` (`producto_id` ASC),
  INDEX `fk_capitulo_tipo_desarrollo1_idx` (`tipo_desarrollo_id` ASC),
  CONSTRAINT `fk_capitulo_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_capitulo_tipo_desarrollo1`
    FOREIGN KEY (`tipo_desarrollo_id`)
    REFERENCES `mydb`.`tipo_desarrollo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato_explotacion_licen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato_explotacion_licen` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_contrato` INT NULL,
  `nit` VARCHAR(45) NULL,
  `nombre_entidad` VARCHAR(45) NULL,
  `certificacion_contrato` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_solicitud` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`solicitud` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero_solicitud` VARCHAR(45) NULL,
  `nombre_solicitante` VARCHAR(45) NULL,
  `anio` DATE NULL,
  `paises` VARCHAR(45) NULL,
  `gaceta_publica` VARCHAR(45) NULL,
  `opiniones_busqueda` VARCHAR(45) NULL,
  `examen_preliminar` VARCHAR(45) NULL,
  `examen_fondo` VARCHAR(45) NULL,
  `tipo_solicitud_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_solicitud_id`),
  INDEX `fk_solicitud_ptc_tipo_solicitud1_idx` (`tipo_solicitud_id` ASC),
  CONSTRAINT `fk_solicitud_ptc_tipo_solicitud1`
    FOREIGN KEY (`tipo_solicitud_id`)
    REFERENCES `mydb`.`tipo_solicitud` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_patente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_patente` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_tecnologico_patentado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_tecnologico_patentado` (
  `id_producto` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `certificado` VARCHAR(45) NULL,
  `titular` VARCHAR(45) NULL,
  `anio_obtencion` VARCHAR NULL,
  `paises_obtencion` VARCHAR(45) NULL,
  `gaceta_publica` VARCHAR(45) NULL,
  `contrato_explotacion_licen_id` INT NULL,
  `id_solicitud` INT NULL,
  `estado_patente` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_patente_solicitud_ptc1_idx` (`id_solicitud` ASC),
  INDEX `fk_patente_contrato_explotacion_licen1_idx` (`contrato_explotacion_licen_id` ASC),
  INDEX `fk_producto_tecnologico_patentado_estado_patente1_idx` (`estado_patente` ASC),
  CONSTRAINT `fk_patente_contrato_explotacion_licen1`
    FOREIGN KEY (`contrato_explotacion_licen_id`)
    REFERENCES `mydb`.`contrato_explotacion_licen` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_patente_solicitud_ptc1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `mydb`.`solicitud` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_tecnologico_patentado_estado_patente1`
    FOREIGN KEY (`estado_patente`)
    REFERENCES `mydb`.`estado_patente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_tecnologico_patentado_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subtipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`subtipo_producto` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `tipo_producto` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subtipo_producto_tipo_producto1_idx` (`tipo_producto` ASC),
  CONSTRAINT `fk_subtipo_producto_tipo_producto1`
    FOREIGN KEY (`tipo_producto`)
    REFERENCES `mydb`.`tipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_tipo_producto` INT NULL,
  `id_subtipo_producto` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categoria_tipo_producto1_idx` (`id_tipo_producto` ASC),
  INDEX `fk_categoria_subtipo_producto1_idx` (`id_subtipo_producto` ASC),
  CONSTRAINT `fk_categoria_tipo_producto1`
    FOREIGN KEY (`id_tipo_producto`)
    REFERENCES `mydb`.`tipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_categoria_subtipo_producto1`
    FOREIGN KEY (`id_subtipo_producto`)
    REFERENCES `mydb`.`subtipo_producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requerimientos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requerimientos` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_requerimientos_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_requerimientos_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`peso_relativo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`peso_relativo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL,
  `categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Peso_relativo_categoria1_idx` (`categoria_id` ASC),
  CONSTRAINT `fk_Peso_relativo_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `mydb`.`categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_vegetal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_vegetal` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_ciclo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_ciclo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`variedad_vegetal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`variedad_vegetal` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `tipo_id` INT NOT NULL,
  `estado_vegetal_id` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_variedad_vegetal_tipo1_idx` (`tipo_id` ASC),
  INDEX `fk_variedad_vegetal_producto1_idx` (`id_producto` ASC),
  INDEX `fk_variedad_vegetal_estado_vegetal1_idx` (`estado_vegetal_id` ASC),
  CONSTRAINT `fk_variedad_vegetal_estado_vegetal1`
    FOREIGN KEY (`estado_vegetal_id`)
    REFERENCES `mydb`.`estado_vegetal` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variedad_vegetal_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_variedad_vegetal_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `mydb`.`tipo_ciclo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estado_raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado_raza` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`nueva_raza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nueva_raza` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `certificado_bioseguridad` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `estado_raza_id` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_nueva_raza_producto1_idx` (`id_producto` ASC),
  INDEX `fk_nueva_raza_estado_raza1_idx` (`estado_raza_id` ASC),
  CONSTRAINT `fk_nueva_raza_estado_raza1`
    FOREIGN KEY (`estado_raza_id`)
    REFERENCES `mydb`.`estado_raza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nueva_raza_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.` artes_arquitectura_diseno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.` artes_arquitectura_diseno` (
  `producto_id` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `fecha_creacion` DATE NULL,
  `fecha_seleccion` DATE NULL,
  `area_conocimiento` VARCHAR(45) NULL,
  `exsitencia_soporte` VARCHAR(45) NULL,
  INDEX `fk_ artes_arquitectura_diseno_producto1_idx` (`producto_id` ASC),
  CONSTRAINT `fk_ artes_arquitectura_diseno_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tecnologicos_certificados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tecnologicos_certificados` (
  `id_producto` INT NOT NULL,
  `numero_registro` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `nombre_titular` VARCHAR(45) NULL,
  `anio_obtencion` VARCHAR NULL,
  `pais_obtencion` VARCHAR(45) NULL,
  `gaceta_publicacion` VARCHAR(45) NULL,
  `descripcion_analisis` VARCHAR(45) NULL,
  `descripcion_diseno` VARCHAR(45) NULL,
  `descripcion_implementacion` VARCHAR(45) NULL,
  `descripcion_validacion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `lugar_elaboracion` VARCHAR(45) NULL,
  `institucion_financiadora` VARCHAR(45) NULL DEFAULT NULL,
  `copia_contratos` VARCHAR(45) NULL,
  `mes` VARCHAR NULL,
  `fecha_elaboracion` VARCHAR NULL,
  `tecnologicos_certificadoscol` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_tecnologicos_certificados_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_tecnologicos_certificados_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`producto_empresarial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`producto_empresarial` (
  `id_producto` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NULL,
  `valor_contrato` VARCHAR(45) NULL,
  `numero_contrato` VARCHAR(45) NULL,
  `nit` VARCHAR(45) NULL,
  `certificado_camara` VARCHAR(45) NULL,
  `certificado_institucional` VARCHAR(45) NULL,
  `autores` VARCHAR(45) NULL,
  `certificacion_implementacion` VARCHAR(45) NULL,
  `documento_ley` VARCHAR(45) NULL,
  `certificacion_producto` VARCHAR(45) NULL,
  `nombre_empresa` VARCHAR(45) NULL,
  `fecha` VARCHAR NULL,
  `titulo` VARCHAR(45) NULL,
  `nombre_innovacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_produtos_empresarial_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_produtos_empresarial_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gpc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gpc` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `anio_expedicion` DATE NULL,
  `ISBN` VARCHAR(45) NULL,
  `copia_contrato` VARCHAR(45) NULL,
  `recibo_isbn` VARCHAR(45) NULL,
  `copia_portada` VARCHAR(45) NULL,
  `copia_preliminar` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_ley`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_ley` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `certificado_senado` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`regulacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`regulacion` (
  `id_producto` INT NOT NULL,
  `entidad_reglamentacion` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `certificado_entidad` VARCHAR(45) NULL,
  `id_gcp` INT NULL,
  `id_proyecto_ley` INT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_regulaiones_GPC1_idx` (`id_gcp` ASC),
  INDEX `fk_regulaiones_proyecto_ley1_idx` (`id_proyecto_ley` ASC),
  INDEX `fk_regulaiones_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_regulaiones_GPC1`
    FOREIGN KEY (`id_gcp`)
    REFERENCES `mydb`.`gpc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regulaiones_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_regulaiones_proyecto_ley1`
    FOREIGN KEY (`id_proyecto_ley`)
    REFERENCES `mydb`.`proyecto_ley` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`consultoria_informe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`consultoria_informe` (
  `id_producto` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `numero_contrato` VARCHAR(45) NULL,
  `documento_consultoria` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `certificacion_empresa` VARCHAR(45) NULL,
  `certificacion_IES` VARCHAR(45) NULL,
  `certifiacion_entidad` VARCHAR(45) NULL,
  `titulo_investigacion` VARCHAR(45) NULL,
  INDEX `fk_consultoria_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_consultoria_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `documento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`acuerdo_licencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`acuerdo_licencia` (
  `producto_id` INT NOT NULL,
  `nombre_obra` VARCHAR(45) NULL,
  `licencia_institucion` VARCHAR(45) NULL,
  `fecha_licencia` DATE NULL,
  `ciudad` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `numero_registro` VARCHAR(45) NULL,
  `proyecto_creacion` VARCHAR(45) NULL,
  `contrato_id` INT NULL,
  INDEX `fk_acuerdo_licencia_contrato1_idx` (`contrato_id` ASC),
  INDEX `fk_acuerdo_licencia_producto1_idx1` (`producto_id` ASC),
  CONSTRAINT `fk_acuerdo_licencia_contrato1`
    FOREIGN KEY (`contrato_id`)
    REFERENCES `mydb`.`contrato` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_acuerdo_licencia_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participacion_ciudada`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participacion_ciudada` (
  `id_producto` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `nombre_comunidad` VARCHAR(45) NULL,
  `instituciones_vincula` VARCHAR(45) NULL,
  `nombre_espacio` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_participacion_ciudada_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_participacion_ciudada_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estrategia_pedagogica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estrategia_pedagogica` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `instituciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_estrategia_pedagogica_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_estrategia_pedagogica_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`circulacion_conocimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`circulacion_conocimiento` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_inic` DATE NULL,
  `fecha_fin` DATE NULL,
  `nombre_participantes` VARCHAR(45) NULL,
  `entidades_gestiona` VARCHAR(45) NULL,
  `organizadores` VARCHAR(45) NULL,
  `lugar` VARCHAR(45) NULL,
  `nombre_comunidad` VARCHAR(45) NULL,
  `pagina_web` VARCHAR(45) NULL,
  `certificado_taller` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `autores` VARCHAR(45) NULL,
  `anio` DATE NULL,
  `instituciones` VARCHAR(45) NULL,
  `DOI` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `ISSN` VARCHAR(45) NULL,
  `ISBN` VARCHAR(45) NULL,
  `nombre_editor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_circulacion_conocimiento_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_circulacion_conocimiento_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reconocimiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reconocimiento` (
  `producto_id` INT NOT NULL,
  `institucion_organizacion` VARCHAR(45) NULL,
  `fecha_otorga` VARCHAR(45) NULL,
  INDEX `fk_reconocimiento_producto1_idx` (`producto_id` ASC),
  CONSTRAINT `fk_reconocimiento_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabajos_tesis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabajos_tesis` (
  `id_producto` INT NOT NULL,
  `titulo` VARCHAR(1000) NULL,
  `institucion` VARCHAR(500) NULL,
  `anio` VARCHAR(45) NULL,
  `reconocimientos` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_trabajos_grado_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_trabajos_grado_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_investigacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_investigacion` (
  `id_producto` INT NOT NULL,
  `titulo` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `entidad_financiadora` VARCHAR(45) NULL,
  `acto_administrativo` VARCHAR(45) NULL,
  `anio` DATE NULL,
  `numero_contrato` VARCHAR(45) NULL,
  INDEX `fk_proyecto_investigacion_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_proyecto_investigacion_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_extension`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_extension` (
  `id_producto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `fecha_ini` DATE NULL,
  `fecha_final` DATE NULL,
  `instituciones` VARCHAR(45) NULL,
  `nombre_comunidades` VARCHAR(45) NULL,
  `resumen_programa` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_proyecto_extension_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_proyecto_extension_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`apoyo_programa_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`apoyo_programa_curso` (
  `id_producto` INT NOT NULL,
  `nombre_programa` VARCHAR(45) NULL,
  `programa_imparte` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `facultad` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `identificacion_acto` VARCHAR(45) NULL,
  `numero_acto` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `producto_id` INT NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_apoyo_programa_curso_producto1_idx` (`id_producto` ASC),
  INDEX `fk_apoyo_programa_curso_producto1_idx1` (`producto_id` ASC),
  CONSTRAINT `fk_apoyo_programa_curso_producto1`
    FOREIGN KEY (`producto_id`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`programa_ondas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`programa_ondas` (
  `id_producto` INT NOT NULL,
  `nombre_proyecto` VARCHAR(45) NULL,
  `registro_programa` VARCHAR(45) NULL,
  `institucion` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `resultados_investigacion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `fk_programa_ondas_producto1_idx` (`id_producto` ASC),
  CONSTRAINT `fk_programa_ondas_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `mydb`.`producto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`objetivo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(500) NULL,
  `id_proyecto` INT NOT NULL,
  `producto` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC),
  INDEX `fk_objetivo_Proyecto1_idx` (`id_proyecto` ASC),
  CONSTRAINT `fk_objetivo_Proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_accion_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_accion_grupo` (
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_grupo` INT NOT NULL,
  INDEX `fk_plan_accion_grupo_Grupo_Investigacion1_idx` (`id_grupo` ASC),
  PRIMARY KEY (`year`, `semestre`, `id_grupo`),
  CONSTRAINT `fk_plan_accion_grupo_Grupo_Investigacion1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad_investigacion_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad_investigacion_grupo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NULL,
  `responsables` VARCHAR(300) NULL,
  `producto` VARCHAR(500) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `estado` INT NULL DEFAULT 0,
  `porcentaje` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_semillero` (
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_semillero` INT NOT NULL,
  INDEX `fk_plan_semillero_Semillero1_idx` (`id_semillero` ASC),
  PRIMARY KEY (`year`, `semestre`, `id_semillero`),
  CONSTRAINT `fk_plan_semillero_Semillero1`
    FOREIGN KEY (`id_semillero`)
    REFERENCES `mydb`.`semillero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`capacitacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `objetivo` VARCHAR(45) NULL,
  `responsables` VARCHAR(45) NULL,
  `n_asistentes` INT NULL,
  `fecha_ini` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `estado` INT NULL,
  `porcentaje` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad_investigacion_semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad_investigacion_semillero` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(300) NULL,
  `responsable` VARCHAR(300) NULL,
  `producto` VARCHAR(500) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_final` VARCHAR(45) NULL,
  `estado` INT NULL DEFAULT 0,
  `porcentaje` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(500) NULL,
  `caracter_evento` VARCHAR(200) NULL,
  `responsables` VARCHAR(200) NULL,
  `instituiones_promo` VARCHAR(200) NULL,
  `entidades_participantes` VARCHAR(200) NULL,
  `fecha_inicio` VARCHAR(45) NULL,
  `fecha_final` VARCHAR(45) NULL,
  `estado` INT NULL,
  `porcentaje` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad_plan_semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad_plan_semillero` (
  `id_actividad` INT NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_semillero` INT NOT NULL,
  PRIMARY KEY (`id_actividad`, `year`, `semestre`, `id_semillero`),
  INDEX `fk_actividad_plan_semillero_actividad_investigacion_semille_idx` (`id_actividad` ASC),
  INDEX `fk_actividad_plan_semillero_plan_semillero1_idx` (`year` ASC, `semestre` ASC, `id_semillero` ASC),
  CONSTRAINT `fk_actividad_plan_semillero_actividad_investigacion_semillero1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `mydb`.`actividad_investigacion_semillero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actividad_plan_semillero_plan_semillero1`
    FOREIGN KEY (`year` , `semestre` , `id_semillero`)
    REFERENCES `mydb`.`plan_semillero` (`year` , `semestre` , `id_semillero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`investigador_externo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`investigador_externo` (
  `id_investigador` INT NOT NULL,
  `institucion_empresa` VARCHAR(45) NULL,
  `cargo` VARCHAR(45) NULL,
  `profesion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_investigador`),
  CONSTRAINT `fk_investigador_externo_investigador1`
    FOREIGN KEY (`id_investigador`)
    REFERENCES `mydb`.`investigador` (`id_investigador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`joven_investigador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`joven_investigador` (
  `id_investigador` INT NOT NULL,
  `propuesta_desarrollada` VARCHAR(45) NULL,
  `periodo_beca` VARCHAR(45) NULL,
  `modalidad` VARCHAR(45) NULL,
  `tutor` INT NOT NULL,
  PRIMARY KEY (`id_investigador`),
  INDEX `fk_joven_investigador_docente_ufps1_idx` (`tutor` ASC),
  CONSTRAINT `fk_joven_investigador_investigador1`
    FOREIGN KEY (`id_investigador`)
    REFERENCES `mydb`.`investigador` (`id_investigador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_joven_investigador_docente_ufps1`
    FOREIGN KEY (`tutor`)
    REFERENCES `mydb`.`docente_ufps` (`id_investigador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudiante` (
  `id_estudiante` INT NOT NULL,
  `codigo` VARCHAR(45) NULL,
  `semestre` VARCHAR(45) NULL,
  `id_programa` INT NOT NULL,
  INDEX `fk_estudiante_programa1_idx` (`id_programa` ASC),
  PRIMARY KEY (`id_estudiante`),
  UNIQUE INDEX `codigo_UNIQUE` (`codigo` ASC),
  CONSTRAINT `fk_estudiante_programa1`
    FOREIGN KEY (`id_programa`)
    REFERENCES `mydb`.`programa` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiante_participante1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `mydb`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`actividad_objetivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`actividad_objetivo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `id_objetivo` INT NOT NULL,
  `porcentaje_avance` VARCHAR(45) NULL,
  `fecha_ini` VARCHAR(45) NULL,
  `fecha_fin` VARCHAR(45) NULL,
  `responsables` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_actividad_objetivo_objetivo1_idx` (`id_objetivo` ASC),
  CONSTRAINT `fk_actividad_objetivo_objetivo1`
    FOREIGN KEY (`id_objetivo`)
    REFERENCES `mydb`.`objetivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_accion_capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_accion_capacitacion` (
  `id_capacitacion` INT NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_semillero` INT NOT NULL,
  PRIMARY KEY (`semestre`, `id_semillero`, `year`, `id_capacitacion`),
  INDEX `fk_plan_semillero_has_capacitacion_capacitacion1_idx` (`id_capacitacion` ASC),
  INDEX `fk_plan_accion_capacitacion_plan_semillero1_idx` (`year` ASC, `semestre` ASC, `id_semillero` ASC),
  CONSTRAINT `fk_plan_accion_capacitacion_plan_semillero1`
    FOREIGN KEY (`year` , `semestre` , `id_semillero`)
    REFERENCES `mydb`.`plan_semillero` (`year` , `semestre` , `id_semillero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_semillero_has_capacitacion_capacitacion1`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `mydb`.`capacitacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_semillero` (
  `id_semillero` INT NOT NULL,
  `id_proyecto` INT NOT NULL,
  PRIMARY KEY (`id_semillero`, `id_proyecto`),
  INDEX `fk_proyecto_grupo_has_Semillero_Semillero1_idx` (`id_semillero` ASC),
  INDEX `fk_proyecto_Semillero_Proyecto1_idx` (`id_proyecto` ASC),
  CONSTRAINT `fk_proyecto_Semillero_Proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_grupo_has_Semillero_Semillero1`
    FOREIGN KEY (`id_semillero`)
    REFERENCES `mydb`.`semillero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evidencia_evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evidencia_evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `id_evento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evidencia_evento1_idx` (`id_evento` ASC),
  CONSTRAINT `fk_evidencia_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participante_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participante_grupo` (
  `id_grupo` INT NOT NULL,
  `id_participante` INT NOT NULL,
  PRIMARY KEY (`id_grupo`, `id_participante`),
  INDEX `fk_participante_grupo_Grupo_Investigacion1_idx` (`id_grupo` ASC),
  INDEX `fk_participante_grupo_participante1_idx` (`id_participante` ASC),
  CONSTRAINT `fk_participante_grupo_Grupo_Investigacion1`
    FOREIGN KEY (`id_grupo`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_grupo_participante1`
    FOREIGN KEY (`id_participante`)
    REFERENCES `mydb`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rol` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participante_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participante_proyecto` (
  `id_proyecto` INT NOT NULL,
  `id_participante` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `horas_semana` INT NULL,
  PRIMARY KEY (`id_proyecto`, `id_participante`),
  INDEX `fk_participante_proyecto_Proyecto1_idx` (`id_proyecto` ASC),
  INDEX `fk_participante_proyecto_rol1_idx` (`id_rol` ASC),
  INDEX `fk_participante_proyecto_participante1_idx` (`id_participante` ASC),
  CONSTRAINT `fk_participante_proyecto_Proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_proyecto_participante1`
    FOREIGN KEY (`id_participante`)
    REFERENCES `mydb`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_proyecto_rol1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `mydb`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_estudio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_estudio` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estudio_investigador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estudio_investigador` (
  `id` VARCHAR(45) NOT NULL,
  `entidad` VARCHAR(45) NULL,
  `titulo` VARCHAR(45) NULL,
  `anio` VARCHAR(45) NULL,
  `tipo_estudio` INT NOT NULL,
  `id_investigador` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estudio_investigador_tipo_estudio1_idx` (`tipo_estudio` ASC),
  INDEX `fk_estudio_investigador_investigador1_idx` (`id_investigador` ASC),
  CONSTRAINT `fk_estudio_investigador_tipo_estudio1`
    FOREIGN KEY (`tipo_estudio`)
    REFERENCES `mydb`.`tipo_estudio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudio_investigador_investigador1`
    FOREIGN KEY (`id_investigador`)
    REFERENCES `mydb`.`investigador` (`id_investigador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`participante_semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participante_semillero` (
  `id_semillero` INT NOT NULL,
  `id_participante` INT NOT NULL,
  INDEX `fk_participante_semillero_Semillero1_idx` (`id_semillero` ASC),
  INDEX `fk_participante_semillero_participante1_idx` (`id_participante` ASC),
  PRIMARY KEY (`id_semillero`, `id_participante`),
  CONSTRAINT `fk_participante_semillero_Semillero1`
    FOREIGN KEY (`id_semillero`)
    REFERENCES `mydb`.`semillero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participante_semillero_participante1`
    FOREIGN KEY (`id_participante`)
    REFERENCES `mydb`.`participante` (`id_participante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_rol` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles_sistema` (
  `id` INT NOT NULL,
  `usuario` VARCHAR(45) NULL,
  `clave` VARCHAR(45) NULL,
  `persona_id` INT NOT NULL,
  `tipo_rol_id` INT NOT NULL,
  PRIMARY KEY (`id`, `tipo_rol_id`),
  INDEX `fk_roles_sistema_persona1_idx` (`persona_id` ASC),
  INDEX `fk_roles_sistema_tipo_rol1_idx` (`tipo_rol_id` ASC),
  CONSTRAINT `fk_roles_sistema_persona1`
    FOREIGN KEY (`persona_id`)
    REFERENCES `mydb`.`persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_roles_sistema_tipo_rol1`
    FOREIGN KEY (`tipo_rol_id`)
    REFERENCES `mydb`.`tipo_rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`linea_semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`linea_semillero` (
  `id` INT NOT NULL,
  `id_semillero` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_linea_semillero_Semillero1_idx` (`id_semillero` ASC),
  CONSTRAINT `fk_linea_semillero_linea_investigacion1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`linea_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_linea_semillero_Semillero1`
    FOREIGN KEY (`id_semillero`)
    REFERENCES `mydb`.`semillero` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evidencia_capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evidencia_capacitacion` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `evidencia` VARCHAR(45) NULL,
  `id_capacitacion` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_evidencia_capacitacion_capacitacion1_idx` (`id_capacitacion` ASC),
  CONSTRAINT `fk_evidencia_capacitacion_capacitacion1`
    FOREIGN KEY (`id_capacitacion`)
    REFERENCES `mydb`.`capacitacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_archivo` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`archivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`archivo` (
  `id` INT NOT NULL,
  `evidencia` VARCHAR(45) NULL,
  `id_evidencia_evento` INT NOT NULL,
  `id_tipo_archivo` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_archivo_evidencia_evento1_idx` (`id_evidencia_evento` ASC),
  INDEX `fk_archivo_tipo_archivo1_idx` (`id_tipo_archivo` ASC),
  CONSTRAINT `fk_archivo_evidencia_evento1`
    FOREIGN KEY (`id_evidencia_evento`)
    REFERENCES `mydb`.`evidencia_evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_archivo_tipo_archivo1`
    FOREIGN KEY (`id_tipo_archivo`)
    REFERENCES `mydb`.`tipo_archivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_accion_grupo_proyecto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_accion_grupo_proyecto` (
  `id_proyecto` INT NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_grupo` INT(11) NOT NULL,
  PRIMARY KEY (`id_proyecto`, `year`, `semestre`, `id_grupo`),
  INDEX `fk_plan_accion_grupo_has_proyecto_proyecto1_idx` (`id_proyecto` ASC),
  INDEX `fk_plan_accion_grupo_proyecto_plan_accion_grupo1_idx` (`year` ASC, `semestre` ASC, `id_grupo` ASC),
  CONSTRAINT `fk_plan_accion_grupo_has_proyecto_proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_accion_grupo_proyecto_plan_accion_grupo1`
    FOREIGN KEY (`year` , `semestre` , `id_grupo`)
    REFERENCES `mydb`.`plan_accion_grupo` (`year` , `semestre` , `id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proyecto_plan_semillero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proyecto_plan_semillero` (
  `id_proyecto` INT(11) NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_semillero` INT NOT NULL,
  PRIMARY KEY (`year`, `semestre`, `id_semillero`, `id_proyecto`),
  INDEX `fk_proyecto_has_plan_semillero_proyecto1_idx` (`id_proyecto` ASC),
  INDEX `fk_proyecto_plan_semillero_plan_semillero1_idx` (`year` ASC, `semestre` ASC, `id_semillero` ASC),
  CONSTRAINT `fk_proyecto_has_plan_semillero_proyecto1`
    FOREIGN KEY (`id_proyecto`)
    REFERENCES `mydb`.`proyecto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_proyecto_plan_semillero_plan_semillero1`
    FOREIGN KEY (`year` , `semestre` , `id_semillero`)
    REFERENCES `mydb`.`plan_semillero` (`year` , `semestre` , `id_semillero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plan_accion_grupo_actividad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`plan_accion_grupo_actividad` (
  `id_actividad` INT NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_grupo` INT(11) NOT NULL,
  PRIMARY KEY (`id_actividad`, `year`, `semestre`, `id_grupo`),
  INDEX `fk_plan_accion_grupo_has_actividad_investigacion_grupo_acti_idx` (`id_actividad` ASC),
  INDEX `fk_plan_accion_grupo_actividad_plan_accion_grupo1_idx` (`year` ASC, `semestre` ASC, `id_grupo` ASC),
  CONSTRAINT `fk_plan_accion_grupo_actividad_plan_accion_grupo1`
    FOREIGN KEY (`year` , `semestre` , `id_grupo`)
    REFERENCES `mydb`.`plan_accion_grupo` (`year` , `semestre` , `id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plan_accion_grupo_has_actividad_investigacion_grupo_activi1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `mydb`.`actividad_investigacion_grupo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`archivo_capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`archivo_capacitacion` (
  `id` INT NOT NULL,
  `evidencia_capacitacion_id` INT NOT NULL,
  `evidencia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_archivo_evidencia_capacitacion1_idx` (`evidencia_capacitacion_id` ASC),
  CONSTRAINT `fk_archivo_evidencia_capacitacion1`
    FOREIGN KEY (`evidencia_capacitacion_id`)
    REFERENCES `mydb`.`evidencia_capacitacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_archivo_capacitacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_archivo_capacitacion` (
  `id` INT NOT NULL,
  `archivo_capacitacion_id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipo_archivo_capacitacion_archivo_capacitacion1_idx` (`archivo_capacitacion_id` ASC),
  CONSTRAINT `fk_tipo_archivo_capacitacion_archivo_capacitacion1`
    FOREIGN KEY (`archivo_capacitacion_id`)
    REFERENCES `mydb`.`archivo_capacitacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`grupo_trabaja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`grupo_trabaja` (
  `id_grupo1` INT NOT NULL,
  `id_grupo2` INT NOT NULL,
  INDEX `fk_grupo_trabaja_grupo_investigacion1_idx` (`id_grupo1` ASC),
  INDEX `fk_grupo_trabaja_grupo_investigacion2_idx` (`id_grupo2` ASC),
  PRIMARY KEY (`id_grupo1`, `id_grupo2`),
  CONSTRAINT `fk_grupo_trabaja_grupo_investigacion1`
    FOREIGN KEY (`id_grupo1`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_grupo_trabaja_grupo_investigacion2`
    FOREIGN KEY (`id_grupo2`)
    REFERENCES `mydb`.`grupo_investigacion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evento_plan_accion_grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evento_plan_accion_grupo` (
  `id_evento` INT NOT NULL,
  `year` VARCHAR(45) NOT NULL,
  `semestre` VARCHAR(45) NOT NULL,
  `id_grupo` INT(11) NOT NULL,
  PRIMARY KEY (`id_evento`, `semestre`, `id_grupo`, `year`),
  INDEX `fk_evento_plan_accion_grupo_evento1_idx` (`id_evento` ASC),
  CONSTRAINT `fk_evento_plan_accion_grupo_evento1`
    FOREIGN KEY (`id_evento`)
    REFERENCES `mydb`.`evento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evento_plan_accion_grupo_plan_accion_grupo1`
    FOREIGN KEY (`year` , `semestre` , `id_grupo`)
    REFERENCES `mydb`.`plan_accion_grupo` (`year` , `semestre` , `id_grupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
